### ISSUE TITLE
Suggestions about DLL settings?

### ISSUE THREAD

**Issue by dluc** [vektonn/vektonn-index#7]
I'm trying to run the example, but I stumble on the usual missing DLL error, any suggestion?

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libfaiss_c' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibfaiss_c, 0x0001): tried: '/usr/local/lib//liblibfaiss_c' (no such file), 'liblibfaiss_c' (no such file), '/usr/local/lib/liblibfaiss_c' (no such file), '/usr/lib/liblibfaiss_c' (no such file), '/usr/local/lib//liblibfaiss_c' (no such file), '/Users/me/workspace/apps/Sandbox/bin/Debug/net6.0/liblibfaiss_c' (no such file)
   at Vektonn.Index.Faiss.FaissApi.faiss_index_factory(IntPtr& p_index, Int32 d, String description, FaissMetricType metric)
   at Vektonn.Index.Faiss.FaissIndex..ctor(Int32 vectorDimension, FaissMetricType metric, HnswParams hnswParams)
   at Vektonn.Index.IndexStoreFactory`2.CreateDenseIndex(String algorithm, Int32 vectorDimension, Dictionary`2 indexParams)
   at Vektonn.Index.IndexStoreFactory`2.Create[TVector](String algorithm, Int32 vectorDimension, Boolean withDataStorage, IEqualityComparer`1 idComparer, Dictionary`2 indexParams)
   at Program.<Main>$(String[] args) in /Users/me/workspace/apps/Sandbox/Program.cs:line 71
   at Program.<Main>(String[] args)
```

csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Vektonn.Index" Version="0.7.1" />
    </ItemGroup>
</Project>
```

The error occurs when calling `indexStoreFactory.Create`

```
var indexStore = indexStoreFactory.Create<DenseVector>(...)
```

**Comment by AndrewKostousov** [comment]
You need to get proper FAISS binary somehow.

Either build it yourself with the provided script [.build-faiss-debian.sh](https://github.com/vektonn/vektonn-index/blob/3879f4218e2660f648686b91af6dd213a605f942/.build-faiss-debian.sh).

Or just copy from already published docker image, like it's done in [CI script](https://github.com/vektonn/vektonn-index/blob/3879f4218e2660f648686b91af6dd213a605f942/.github/workflows/ci.yml#L48).

Note that Vektonn + FAISS is supported on Linux only. On Windows you can use WSL to run tests/examples which require FAISS.

**Comment by Sankalp991** [comment]
@dluc  were you able to resolve this issue?
